### ISSUE TITLE
Unable to pip install this package

### ISSUE THREAD

**Issue by StevenDaveySBSA** [looking-for-a-job/dict.py#1]
Hi. Please see the following error messages while trying to install the package
PS C:\sd\SBSA\Code> pip install dict
Looking in indexes: http://pypi.standardbank.co.za/risk/pypi
Collecting dict
Installing collected packages: dict
ERROR: Exception:
Traceback (most recent call last):
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\commands\install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_re
qs
    **kwargs
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\req\req_install.py", line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\req\req_install.py", line 448, in move_wheel_f
iles
    warn_script_location=warn_script_location,
  File "c:\sd\programming\python\anaconda\lib\site-packages\pip\_internal\wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: dict .dist-info directory not found

**Comment by andrewpetrochenkov** [comment]
I can't reproduce and fix the error because I don't have Windows :) p.s.: This is worthless package. you don't need it
